"use strict";
console.log('1');
console.log(5);
let n = 4;
console.log(n);
let n1;
n1 = 99;
console.log(n1);
n = +'3';
console.log(n);
const n2 = 77;
console.log(n2);
const s1 = 'hello';
const s2 = ' TS';
console.log(s1 + s2);
let s3;
s3 = 4;
console.log(s3, typeof s3);
const b1 = false;
console.log(b1, typeof b1);
const c1 = Number('333');
console.log(c1);
const c2 = String(888);
console.log(c2);
const c3 = Boolean(10);
console.log(c3);
document.querySelector('.out-1').textContent = String(c3);
const n5 = +document.querySelector('.out-2').textContent;
console.log(n5, typeof n5);
//# sourceMappingURL=script.js.map